all:
  hosts:
    node1:
      ansible_host: 164.90.170.230
      ip: 164.90.170.230
      access_ip: 164.90.170.230
    node2:
      ansible_host: 164.90.170.243
      ip: 164.90.170.243
      access_ip: 164.90.170.243
    node3:
      ansible_host: 134.209.242.137
      ip: 134.209.242.137
      access_ip: 134.209.242.137
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
