all:
  hosts:
    node1:
      ansible_host: 157.230.20.0
      ip: 157.230.20.0
      access_ip: 157.230.20.0
    node2:
      ansible_host: 157.230.28.41
      ip: 157.230.28.41
      access_ip: 157.230.28.41
    node3:
      ansible_host: 157.230.25.29
      ip: 157.230.25.29
      access_ip: 157.230.25.29
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
