all:
  hosts:
    node1:
      ansible_host: 167.71.36.37
      ip: 167.71.36.37
      access_ip: 167.71.36.37
    node2:
      ansible_host: 159.89.31.155
      ip: 159.89.31.155
      access_ip: 159.89.31.155
    node3:
      ansible_host: 157.230.115.158
      ip: 157.230.115.158
      access_ip: 157.230.115.158
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
